### ISSUE TITLE
[Android Bootcamp] Group Project: Timeline - Ready for Review

### ISSUE THREAD

**Issue by dbautist** [codepath-project-stories/timeline#1]
Our user stories and wireframes are ready for review. /cc @codepathreview @codepath

**Comment by nickai** [comment]
Thanks for submitting this and documenting your progress so far! Good to see you have an initial version of the wireframes complete as a starting point for your app.

Remember that by the end of your second sprint, we expect each team to have their core flows functionally complete (but rough) so this week your team should complete the first 50% of your core functionality.

While building this app, try to keep in your mind the story for your app and what you need to have a polished demo. Be aggressive about which features you can scope into the first version for demo day. Excited to see what your group comes up with! Let us know what we can do to help.

**Comment by Marusya82** [comment]
Our first sprint is ready for review /cc @codepathreview @codepath. Please check out dev branch for code and demo GIF.

We have parse server set up and running, will need to add meaningful data to it, for now data is populated manually.

We have a few features we are working on right now, like animated population of stories, shareable elements between activities, etc.

Also here are a few sketches of screens for how they will look in a few days:
![pasted image at 2016_08_21 10_36 pm](https://cloud.githubusercontent.com/assets/3505078/17871993/f8962e16-6872-11e6-976f-f65aeefe75e5.png)
![pasted image at 2016_08_21 10_37 pm 2](https://cloud.githubusercontent.com/assets/3505078/17872001/0029fa86-6873-11e6-98fc-d0138aa7dbda.png)
![pasted image at 2016_08_21 10_37 pm 1](https://cloud.githubusercontent.com/assets/3505078/17872012/05f0aabe-6873-11e6-9930-9ada7fe10ac6.png)
