### ISSUE TITLE
Permissions generator - please read

### ISSUE THREAD

**Issue by Marusya82** [codepath-project-stories/timeline#13]
If you pull latest changes and run the app - it won't compile. In "NewStoryActivity" class, uncomment everything related to permissions (basically everything that turns red in your code), except for these:

 @NeedsPermission(Manifest.permission.ACCESS_COARSE_LOCATION)
    void accessLocation() {
        // Trigger the access to a location
    }

```
@NeedsPermission(Manifest.permission.CAMERA)
void openCamera() {
    // Trigger the opening of a camera
}

@NeedsPermission(Manifest.permission.READ_EXTERNAL_STORAGE)
void readStorage() {
    // Trigger the reading storage
}

@NeedsPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
void writeStorage() {
    // Trigger the writing to storage
}
```

Run again, it will compile and generate a class "NewStoryActivityPermissionsDispatcher", then you can uncomment the code and it will compile fine.

http://guides.codepath.com/android/Managing-Runtime-Permissions-with-PermissionsDispatcher

@leoliu1313 @dbautist

**Comment by dbautist** [comment]
thanks!
