### ISSUE TITLE
Sprint 3: Poll server for new story/moment

### ISSUE THREAD

**Issue by Marusya82** [codepath-project-stories/timeline#27]

**Comment by Marusya82** [comment]
Hey Ching-yao, today was our "internal" deadline for this. Will you be able to finish it? And when?
@leoliu1313

**Comment by leoliudeprecated** [comment]
I will start working on it after the dinner. Probably finish it in the late
night.

**Comment by dbautist** [comment]
@leoliu1313 @Marusya82 : I should probably do this since this might require updating the cache policy for our queries. @leoliu1313, is that okay?

@leoliu1313: Maybe you can finish up the zoom in/out instead?

**Comment by leoliudeprecated** [comment]
No problem. Thanks for the help.

**Comment by Marusya82** [comment]
I thought zoom in zoom out is done? @leoliu1313 @dbautist I can't test it on the emulator, but remember after the class on Monday it was working on Ching-yao's phone

**Comment by leoliudeprecated** [comment]
Not yet. I try to rebuild it like Dianne suggested. I am trying to
understand Sony Album App and Google Photo App. I can finish it today.

**Comment by Marusya82** [comment]
Sony Album App and Google Photo App? Why? I feel like I am missing smth.. @leoliu1313

**Comment by dbautist** [comment]
Only refreshing moments list: https://github.com/codepath-project-stories/timeline/pull/48

Don't think there's a need to auto-refresh shared stories for v1?

**Comment by Marusya82** [comment]
I agree, no need for now

**Comment by leoliudeprecated** [comment]
a92c23e68f6949c08f517b5cb588efe150896d04
