### ISSUE TITLE
Sprint 3: Fix app crash during the autoplay of last moment

### ISSUE THREAD

**Issue by Marusya82** [codepath-project-stories/timeline#40]

**Comment by Marusya82** [comment]
Done

**Comment by leoliudeprecated** [comment]
crash when scrolling back/left very fast

**Comment by Marusya82** [comment]
Assigning this to you since you know what is up @leoliu1313

**Comment by Marusya82** [comment]
Opened new one with a different name, the issue of a crash while palying last moment is fixed.
8d7ef2e

**Comment by leoliudeprecated** [comment]
I see. Well done. I will fix that one.
