### ISSUE TITLE
Sprint 3: Fix collaborators list search accord. to the API, beautify the layout

### ISSUE THREAD

**Issue by Marusya82** [codepath-project-stories/timeline#43]

**Comment by dbautist** [comment]
We probably don't need this for v1 esp since we don't have a friends list flow? Otherwise, we'd have to create a lot of fake users to demo the search functionality.

**Comment by dbautist** [comment]
Take it back, creating many users for the demo

**Comment by leoliudeprecated** [comment]
https://github.com/codepath-project-stories/timeline/pull/77
