### ISSUE TITLE
Pushed my files - have issues

### ISSUE THREAD

**Issue by Marusya82** [codepath-project-stories/timeline#5]
Hey guys, I pushed landing page activity, but it is not quite working (doesn't generate the list of stories), but it compiles. I will look into it tomorrow before we meet. But if you pull and want to see Dianne's work - just change the main activity in the manifest from landing to timeline activity so that it gets ignored.
@leoliu1313 @dbautist

**Comment by dbautist** [comment]
Thanks @Marusya82. I pulled your changes and it compiles. You can do something like this:

`List<Story> storyList = MockResponseGenerator.getInstance().getStoryList();`

to get some mock stories.

**Comment by Marusya82** [comment]
@dbautist Yeah I did that, but I had an error in the adapter actually..
 All fixed, looks pretty crap, but will work on that! :)
