### ISSUE TITLE
Spring 3: Update number of moments in the story view holder

### ISSUE THREAD

**Issue by Marusya82** [codepath-project-stories/timeline#52]

**Comment by leoliudeprecated** [comment]
https://github.com/codepath-project-stories/timeline/commit/5fd364faabbfc9b7ab38cbe574f5f5a82a9b143b

**Comment by Marusya82** [comment]
Number of moments has to be updated when new moment is added as well.

**Comment by leoliudeprecated** [comment]
That's right. I forgot this kind of situations.

**Comment by dbautist** [comment]
Because we're auto-refreshing the stories list, the number of moments should also be refreshed. No code changes needed unless we switch from auto-refresh to push notification.

Closing for now. https://github.com/codepath-project-stories/timeline/pull/87
