### ISSUE TITLE
Sprint 3: Crash on autoplay when scrolling back/left very fast

### ISSUE THREAD

**Issue by Marusya82** [codepath-project-stories/timeline#53]

**Comment by leoliudeprecated** [comment]
And also this. Is it expected?
http://i.imgur.com/a8b92mB.jpg

**Comment by Marusya82** [comment]
Don't know, you are not supposed to scroll on the autoplay I think?

**Comment by leoliudeprecated** [comment]
Ya, maybe override the listener and just ignore it. Or, fix this kind of issue later. Low priority.

**Comment by leoliudeprecated** [comment]
@dbautist fixed it.
