### ISSUE TITLE
Sprint 3: Change gradient on the item story in the landing page

### ISSUE THREAD

**Issue by Marusya82** [codepath-project-stories/timeline#59]
@dbautist For some reason can't find where you set the overlay image on top of the background image of a story in the landing page. Could you play with it? Like maybe add shadow at the right bottom corner, or like gradient from transparent to black? So that it doesn't eat up the quality of the whole photo, just the corner where the text is. Pictures will pop out much more I believe.

**Comment by dbautist** [comment]
Yeah, was thinking of that as well. I'll play with adding shadow to the text. Thanks!

**Comment by dbautist** [comment]
Let me know what you think: https://github.com/codepath-project-stories/timeline/pull/64
