### ISSUE TITLE
Sprint 3: MY STORIES and FRIENDS STORIES

### ISSUE THREAD

**Issue by leoliudeprecated** [codepath-project-stories/timeline#78]
http://i.imgur.com/72kzSqB.png
replace MY STORIES and FRIENDS STORIES?
1. to NavigationView
2. to icon

**Comment by Marusya82** [comment]
What exactly are you trying to do with the view pager?

**Comment by leoliudeprecated** [comment]
this is open topic. the thing is usually the app in the market doesn't
have view
pager like this.

**Comment by Marusya82** [comment]
I am sure other apps use it, like tweeter in the moments feed? in our case it makes sense for the user to easy switch between two fragments by swiping left and right (user's stories and friend's stories), it also makes it more visible, I don't like the idea of going to the nav bar to do that

**Comment by Marusya82** [comment]
we can look for icons though that can reflect the user's stories and friends' stories and replace the letters or make letters smaller etc. play with it

**Comment by Marusya82** [comment]
@dbautist  need your input to decide on that

**Comment by Marusya82** [comment]
5ed81cb
