### ISSUE TITLE
Sprint 3: progress animation (play with the size)

### ISSUE THREAD

**Issue by leoliudeprecated** [codepath-project-stories/timeline#80]
http://i.imgur.com/SqWAA4l.png
find a better progress animation to replace this?
or don't use progress animation. use transition animation instead.

**Comment by Marusya82** [comment]
I like the current progress animation and already spent time on working on that, don't understand the need to change that?

**Comment by leoliudeprecated** [comment]
can we discuss this and make the decision by three of us? i didn't see your
pull request

**Comment by Marusya82** [comment]
what pull request are you talking about?

**Comment by leoliudeprecated** [comment]
your pull request when making this change

**Comment by Marusya82** [comment]
it was ages ago Ching-yao, you are kinda late on this. I asked everyone on slack and we agreed with Dianne on the progress bar, if you think this is necessary to change this now we can talk about again it when Dianne comes online.

**Comment by leoliudeprecated** [comment]
i just want to bring this up, so we can discuss this again.

**Comment by leoliudeprecated** [comment]
make it a little smaller? i don't know.
https://github.com/81813780/AVLoadingIndicatorView

**Comment by Marusya82** [comment]
You can read the feed about it here on slack https://codepathuniversity.slack.com/archives/G20HNMEUQ/p1472528890000011

Sure, we can make it smaller, like the medium size? At the moment it is set to large. Or maybe change of color to primary will make you happy?

**Comment by leoliudeprecated** [comment]
i remember this. i just feel maybe we can discuss this, and polish it a bit. if you don't want to, that's fine.

**Comment by Marusya82** [comment]
This was in my previous comment "Sure, we can make it smaller, like the medium size? At the moment it is set to large. Or maybe change of color to primary will make you happy?", doesn't it look like I am open to polish? I just don't feel comfortable with the idea of a deeper change, like replacing it with a different progress bar and disregarding other people work and doing all of it on the day when we are doing code freeze, we need to polish small things and look for bugs. The deeper changes to the flow and UI we can discuss after the internal demo.

**Comment by Marusya82** [comment]
Changed the color, will close for now:
https://codepathuniversity.slack.com/archives/G20HNMEUQ/p1473100465000041
