### ISSUE TITLE
consistent button style (space, height, and color)

### ISSUE THREAD

**Issue by leoliudeprecated** [codepath-project-stories/timeline#96]
from @dbautist 

> Perhaps we can create a standard button style so that it can be consistently used throughout the app? This is the current style for the "POST" button from the detail view. See 
> https://github.com/codepath-project-stories/timeline/blob/dev/app/src/main/res/drawable/primary_dark_button.xml
> https://cloud.githubusercontent.com/assets/3712632/18256487/e24b7848-736a-11e6-9dfb-f2381680f3e0.png

my phone looks like this. it is gray button. maybe it is sdk 22 issue? maybe try to reproduce the issue by using sdk 22 emulator if you are interested
http://i.imgur.com/GPRDjMy.jpg

maybe we can have a consistent button style for the following three buttons
1. New story button: need more left/right space
https://cloud.githubusercontent.com/assets/3505078/18257817/eb5da3a2-737e-11e6-9c1a-99d824f6a262.png
http://i.imgur.com/oYrRcFZ.png
2. New moment button: need smaller height
https://cloud.githubusercontent.com/assets/3505078/18257818/eb5e6026-737e-11e6-9913-8a79bf3d0c85.png
3. New comment button: need consistent color
https://cloud.githubusercontent.com/assets/3712632/18256487/e24b7848-736a-11e6-9dfb-f2381680f3e0.png
http://i.imgur.com/GPRDjMy.jpg

// please don't modify my words. use comments. thanks.

**Comment by Marusya82** [comment]
It is gray because it is disabled at first, when you click on it - it is enabled and turns dark primary color

**Comment by leoliudeprecated** [comment]
I see. Feel a little inconsistent.

**Comment by leoliudeprecated** [comment]
improved by @Marusya82 or @dbautist so close it for now. will discuss New comment button in the future.

choice 1
gray. after typing something, green

choice 2
green like New story/moment button
